version: "3"
services:

  boatsandjoy-client:
    build:
      context: .
    volumes:
      - ".:/code/"
      - "/code/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - hot-reloader
    command: npm run serve

  hot-reloader:
    image: bertini36/tailwind-hot-reloader
    volumes:
      - ".:/code/"
    working_dir: /code/
    tty: true
    command: postcss src/assets/main.css -o public/css/output.css -w

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    depends_on:
      - boatsandjoy-client
    command: ngrok http boatsandjoy-client:3000 -host-header="localhost:3000"
